version: "3.3"
services:
  redis:
    image: redis:5.0
    ports:
      - 6379:6379
  mongo:
    image: mongo:5.0
    restart: always
    container_name: lila_mongo
    ports:
      - 27017:27017
    volumes:
      # use `docker exec -it lila_mongo bash` to get a shell inside mongo
      # container. Directory containing this docker-compose.yml will be mounted
      # as /host inside container so you can import db dumps, etc.
      - .:/host
      - lila_mongo_data:/data/db

volumes:
  lila_mongo_data: {}
